### ISSUE TITLE
explore area update

### ISSUE THREAD

**Issue by mainyahhooo** [vi-evans/goatlings-accesibility#1]
this is like, the perfect mod. it could only be improved with the ability to click explore again , since the motion of going from a keyboard to the mouse causes even more strain on my wrist personally than just playing with the mouse fully

**Comment by mainyahhooo** [comment]
i tried to code it myself with little to no success </3

**Comment by goofpunk** [comment]
Hi! Sorry this response is so late, I didn't see this issue here, but this bug was fixed last year.
